/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.multiproject;

import com.epam.multiproject.util.Utils;

public class App {
    public static void main(String[] args) {
        Utils utils = new Utils();
        System.out.println(utils.isAllPositiveNumbers("12", "79"));
    }
}
